-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 17:49:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hackathon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hackathon` ;

-- -----------------------------------------------------
-- Schema hackathon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hackathon` DEFAULT CHARACTER SET utf8 ;
USE `hackathon` ;

-- -----------------------------------------------------
-- Table `hackathon`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hackathon`.`user` ;

CREATE TABLE IF NOT EXISTS `hackathon`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `birthYear` INT NOT NULL,
  `sex` ENUM("male", "female") NOT NULL,
  `placeOfResidence` ENUM("village", "small town", "mid town", "big town") NOT NULL,
  `additionalInformation` LONGTEXT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathon`.`training_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hackathon`.`training_session` ;

CREATE TABLE IF NOT EXISTS `hackathon`.`training_session` (
  `sessionId` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM("image", "audio") NOT NULL,
  `age` INT NOT NULL,
  `startedAt` DATETIME NOT NULL,
  `endedAt` DATETIME NOT NULL,
  `user_userId` INT NOT NULL,
  PRIMARY KEY (`sessionId`, `user_userId`),
  INDEX `fk_training_session_user1_idx` (`user_userId` ASC) VISIBLE,
  CONSTRAINT `fk_training_session_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `hackathon`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathon`.`emotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hackathon`.`emotion` ;

CREATE TABLE IF NOT EXISTS `hackathon`.`emotion` (
  `emotionId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`emotionId`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `hackathon`.`resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hackathon`.`resource` ;

CREATE TABLE IF NOT EXISTS `hackathon`.`resource` (
  `resourseId` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(60) NOT NULL,
  `type` ENUM("image", "audio") NOT NULL,
  `age` ENUM("child", "young adult", "middle-aged adults", "old-aged adults") NULL,
  `sex` ENUM("male", "female") NULL,
  `imageCategory` ENUM("face", "full-body") NULL,
  `emotion_emotionId` INT NOT NULL,
  PRIMARY KEY (`resourseId`, `emotion_emotionId`),
  INDEX `fk_resource_emotion1_idx` (`emotion_emotionId` ASC) VISIBLE,
  CONSTRAINT `fk_resource_emotion1`
    FOREIGN KEY (`emotion_emotionId`)
    REFERENCES `hackathon`.`emotion` (`emotionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathon`.`training_session_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hackathon`.`training_session_result` ;

CREATE TABLE IF NOT EXISTS `hackathon`.`training_session_result` (
  `resultId` INT NOT NULL AUTO_INCREMENT,
  `startedAt` DATETIME NOT NULL,
  `endedAt` DATETIME NOT NULL,
  `emotion_emotionId` INT NOT NULL,
  `training_session_sessionId` INT NOT NULL,
  `training_session_user_userId` INT NOT NULL,
  `resource_resourseId` INT NOT NULL,
  `resource_emotion_emotionId` INT NOT NULL,
  PRIMARY KEY (`resultId`, `emotion_emotionId`, `training_session_sessionId`, `training_session_user_userId`, `resource_resourseId`, `resource_emotion_emotionId`),
  INDEX `fk_training_session_result_emotion1_idx` (`emotion_emotionId` ASC) VISIBLE,
  INDEX `fk_training_session_result_training_session1_idx` (`training_session_sessionId` ASC, `training_session_user_userId` ASC) VISIBLE,
  INDEX `fk_training_session_result_resource1_idx` (`resource_resourseId` ASC, `resource_emotion_emotionId` ASC) VISIBLE,
  CONSTRAINT `fk_training_session_result_emotion1`
    FOREIGN KEY (`emotion_emotionId`)
    REFERENCES `hackathon`.`emotion` (`emotionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_training_session_result_training_session1`
    FOREIGN KEY (`training_session_sessionId` , `training_session_user_userId`)
    REFERENCES `hackathon`.`training_session` (`sessionId` , `user_userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_training_session_result_resource1`
    FOREIGN KEY (`resource_resourseId` , `resource_emotion_emotionId`)
    REFERENCES `hackathon`.`resource` (`resourseId` , `emotion_emotionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO hackathon.emotion (name) 
VALUES ('anger'),
('contempt'),
('fear'),
('disgust'),
('happiness'),
('sadness'),
('surprise');


